/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "surface-container-highest": "#e3e1e9",
        "surface-container-high": "#e9e7ef",
        "outline-variant": "#c5c5d3",
        "inverse-primary": "#b6c4ff",
        "secondary-fixed-dim": "#c5c6c8",
        "inverse-surface": "#2f3036",
        "secondary-container": "#dee0e2",
        "on-secondary-container": "#606365",
        "on-tertiary-container": "#f39461",
        "tertiary-fixed-dim": "#ffb691",
        "on-tertiary-fixed": "#341100",
        "on-primary-fixed": "#00164e",
        "on-secondary-fixed-variant": "#444749",
        "primary": "#00236f",
        "outline": "#757682",
        "secondary-fixed": "#e1e2e4",
        "secondary": "#5c5f60",
        "on-secondary-fixed": "#191c1e",
        "tertiary-container": "#6e2c00",
        "tertiary": "#4b1c00",
        "primary-container": "#1e3a8a",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#f4f3fa",
        "surface": "#faf8ff",
        "surface-container": "#eeedf4",
        "surface-dim": "#dad9e1",
        "on-primary": "#ffffff",
        "background": "#faf8ff",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#4059aa",
        "primary-fixed": "#dce1ff",
        "on-primary-fixed-variant": "#264191",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#773205",
        "on-surface-variant": "#444651",
        "surface-bright": "#faf8ff",
        "inverse-on-surface": "#f1f0f7",
        "tertiary-fixed": "#ffdbcb",
        "on-background": "#1a1b21",
        "on-surface": "#1a1b21",
        "primary-fixed-dim": "#b6c4ff",
        "on-primary-container": "#90a8ff",
        "on-error": "#ffffff",
        "error": "#ba1a1a",
        "warning-container": "#ffecb3",
        "on-warning-container": "#5f4b00",
        "warning": "#f59e0b",
        "surface-variant": "#e3e1e9",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "container-margin": "24px",
        "stack-compact": "8px",
        "table-cell-padding-x": "12px",
        "gutter": "16px",
        "base": "4px",
        "table-cell-padding-y": "8px",
        "stack-loose": "20px",
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "display-lg": ["Hanken Grotesk", "sans-serif"],
        "label-uppercase": ["Inter", "sans-serif"],
        "title-sm": ["Inter", "sans-serif"],
        "data-tabular": ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-uppercase": ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "title-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "data-tabular": ["13px", { lineHeight: "16px", fontWeight: "450" }],
      },
    },
  },
  plugins: [],
}
